// Generated by CoffeeScript 1.10.0
(function() {
  var Awaiter;

  module.exports = Awaiter = (function() {
    function Awaiter() {
      this.awaitee = null;
      this._prev = null;
      this._next = null;
      this.value = void 0;
      this.isFinal = false;
    }

    Awaiter.prototype.block = function(awaitee, value1) {
      this.awaitee = awaitee;
      this.value = value1;
    };

    Awaiter.prototype.proceed = function(value, isFinal) {};

    Awaiter.prototype.register = function(value, isFinal) {
      this.isFinal = isFinal;
      return this.value = value;
    };

    return Awaiter;

  })();

}).call(this);
