// Generated by CoffeeScript 1.9.2
(function() {
  var Awaiter, Callback, pooled,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  pooled = require('./helpers').pooled;

  Awaiter = require('./awaiter');

  module.exports = pooled(Callback = (function(superClass) {
    extend(Callback, superClass);

    function Callback(channel, fn, context) {
      Callback.__super__.constructor.apply(this, arguments);
      this.channel = channel;
      this.fn = fn;
      this.context = context;
    }

    Callback.prototype.proceed = function(value, isFinal) {
      var ref, result;
      result = (ref = this.fn) != null ? ref.call(this.context, this.channel, value, isFinal) : void 0;
      this.free();
      return result;
    };

    return Callback;

  })(Awaiter));

}).call(this);
