// Generated by CoffeeScript 1.10.0
(function() {
  var Executor;

  module.exports = Executor = (function() {
    function Executor() {
      this.awaitee = null;
      this._prev = null;
      this._next = null;
      this.value = void 0;
      this.isFinal = false;
    }

    Executor.prototype.block = function(awaitee, value1) {
      this.awaitee = awaitee;
      this.value = value1;
    };

    Executor.prototype.proceed = function(value, isFinal) {};

    Executor.prototype.register = function(value, isFinal) {
      this.isFinal = isFinal;
      return this.value = value;
    };

    return Executor;

  })();

}).call(this);
